services:
  - type: web
    name: pensa-ttu-api
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PRAYER_ADMIN_PASSWORD_HASH
        sync: false
      - key: SEC_DB_NAME
        value: u197926764_pensattu
      - key: SEC_JWT_SECRET
        sync: false
      - key: ARKESEL_API_KEY
        sync: false
      - key: ARKESEL_SENDER_ID
        value: PENSA-TTU
